options:
  window_manager: "hyprland" # hyprland or sway
  global_mango_hud: true

packages:
  nvidia: true # Install and configure Nvidia driver
  bluetooth: true # Install bluetooth applet
  sddm: true # install and configure sddm (including theme if dotfiles are installed)
  extras: true # Install extra packages (see extras section in distro/packages.yml)
  dotfiles: true # Install sorcerer's dotfiles

flatpak:
  packages:
    devel: true
    extras: true
    misc: true
