options:
  window_manager: "hyprland" # hyprland or sway
  firewall: true
  network_shares: false # Disabled until I figure a good way to do it
  auto_login: false # TODO Find out why SDDM breaks when using autologin on arch

# To map network shares you have to create a shares.yml file with an array of strings which will be added to /etc/fstab:

#   - //<host> /<target> cifs credentials=$HOME/.smb_credentials,uid=1000,gid=1000,file_mode=0775,dir_mode=0775,_netdev,iocharset=utf8,noperm 0 0

# You also have to create the .smb_credentials file in your home directory with the following structure:

# username=<share user name>
# password=<share password>

packages:
  nvidia: true # Install and configure Nvidia driver
  bluetooth: true # Install bluetooth applet
  sddm: true # install and configure sddm (including theme if dotfiles are installed)
  extras: true # Install extra packages (see extras section in distro/packages.yml)
  dotfiles: true # Install sorcerer's dotfiles
  nvim: true # Install sorcerer's NeoVim config

flatpak:
  packages:
    devel: true
    extras: true
    misc: true

dotfiles_repo:
  url: https://github.com/sorcererlc/dotfiles.git

nvim_repo:
  url: https://github.com/sorcererlc/nvim.git

shares_file: "shares.yml" # Path to a yaml file containing an array of strings to be added to /etc/fstab
